FROM python:3.14-slim-bookworm
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
WORKDIR /tmp
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN mkdir -p /app
WORKDIR /app
